version: '3.7'

services:
  api:
    container_name: jump-api
    build: .
    env_file: .env
    ports:
      - 3001:3001
    command: /bin/bash -c "/srv/app/entrypoint.sh"
    depends_on:
      - db
      - mailhog
      - localstack

  db:
    container_name: jump-marketplace-database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketplace
    ports:
      - 7432:5432
    volumes:
      - jump_marketplace_postgres:/var/lib/postgresql/data

  mailhog:
    container_name: jump-marketplace-mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4583:4566-4583"
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  jump_marketplace_postgres:
