version: '3.1'

services:

  db:
    container_name: jump-marketplace-database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketplace
    ports:
      - 7432:5432
    volumes:
      - jump_marketplace_postgres:/var/lib/postgresql/data

  mailhog:
    container_name: jump-marketplace-mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  jump_marketplace_postgres:
