version: '3.7'

services:
  app:
    container_name: jump-api
    build: .
    volumes:
      - ..:/workspace:cached
      - node-modules:/workspace/node_modules:rw
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - MAILER_HOST=mailhog
    ports:
      - 3001:3001
      - 4566:4566
  httpstatus:
    image: ghcr.io/lucky/httpstatus:latest
  postgres:
    container_name: jump-database
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketplace
    volumes:
      - jump_marketplace_postgres:/var/lib/postgresql/data

  mailhog:
    container_name: jump-mailhog
    image: luckythetourist/mailhog
    ports:
      - 8025:8025
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - EDGE_PORT=4566
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "service:app"

volumes:
  jump_marketplace_postgres:
  node-modules:
