name: 'Test & Deploy - Develop'
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  main:
    name: 'Test & Deploy'
    runs-on: ubuntu-latest
    steps:
      ######################################
      # Build, Install and Test
      ######################################
      - name: 'Checkout source code'
        uses: actions/checkout@v2

      - name: 'Setup NodeJS 14'
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: 'Install Dependencies'
        run: yarn install

      - name: 'Build'
        run: yarn build

      - name: 'Run Tests'
        run: yarn test

      ######################################
      # Deploy to Elastic Beanstalk
      ######################################
      - name: 'Generate Deployment Package'
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: zip -r deploy.zip . -x '*.git*'

      - name: 'Generate Version Label'
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        run: echo VERSION_LABEL=build--$(date +%s) >> $GITHUB_ENV

      - name: 'Deploy to Elastic Beanstalk'
        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'Marketplace API'
          environment_name: ${{ secrets.AWS_ENVIORNMENT_NAME_STAGING }}
          version_label: ${{ env.VERSION_LABEL }}
          version_description: ${{ env.VERSION_LABEL }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip