name: "Test"
on:
  pull_request:
    branches:
      - "**"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  main:
    name: "Test"
    runs-on: ubuntu-latest
    container: node:16
    services:
      httpstatus:
        image: ghcr.io/lucky/httpstatus:latest
        ports:
          - 3999/tcp
      localstack:
        image: localstack/localstack:latest
        env:
          AWS_DEFAULT_REGION: us-west-2
          EDGE_PORT: 4566
          SERVICES: s3
        ports: ["4566:4566"]
      postgres:
        image: postgres
        env:
          POSTGRES_PORT: 5432
          POSTGRES_DB: "test"
          POSTGRES_USERNAME: "postgres"
          POSTGRES_PASSWORD: "password"
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: "Setup NodeJS 16"
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: yarn.lock
      - name: "Install Dependencies"
        run: yarn install
      - name: "Build"
        run: yarn build
      - name: "Bundle"
        run: yarn bundle
      - name: "Run Tests"
        run: yarn test
        env:
          NODE_ENV: test
          AWS_ENDPOINT: http://localstack:4566
